source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Moya-JASONMapper_Example', :exclusive => true do
  pod 'Moya-JASONMapper', :path => '../'
  pod 'Moya-JASONMapper/RxSwift', :path => '../'
  pod 'Moya-JASONMapper/ReactiveCocoa', :path => '../'
end

target 'Moya-JASONMapper_Tests', :exclusive => true do
  pod 'Moya-JASONMapper', :path => '../'
  pod 'Moya-JASONMapper/RxSwift', :path => '../'
  pod 'Moya-JASONMapper/ReactiveCocoa', :path => '../'
  
end
