source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

def sharedPods
    pod 'JASON'
    pod 'Moya'
    pod 'Moya-JASONMapper', :path => '../'
    pod 'Moya-JASONMapper/RxSwift', :path => '../'
    pod 'Moya-JASONMapper/ReactiveSwift', :path => '../'
end

target 'Moya-JASONMapper_Example' do
  sharedPods
end

target 'Moya-JASONMapper_Tests' do
  sharedPods
end

# Build configurations
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
